recipes/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import *
from django.contrib.auth.models import User
from models import Recipe, FoodPicture, UserForm
from views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^contents/$',RecipeListView.as_view(
            queryset=Recipe.objects.all().order_by('dish','name'),
            template_name='recipes/contents_dev.html'
            ), 
        name='recipe_contents'),
    url(r'^index/$',RecipeListView.as_view(
            queryset=Recipe.objects.all().order_by('name'),
            template_name='recipes/index_dev.html'
            ), 
        name='recipe_index'),
    url(r'^search/$',SearchListView.as_view(template_name='recipes/search_dev.html'), 
        name='recipe_search'),
    url(r'^(?P<slug>[-\w]+)/$', RecipeDetailView.as_view(),name='recipe_detail'),
    url(r'^(?P<slug>[-\w]+)/picture/$', PictureAddView.as_view()), 
    url(r'^fav/(?P<recipe_slug>[-\w]+)/$',FavView.as_view(),name='add_favorite'),
    url(r'^user/(?P<username>[^/]+)/$',RecipeListView.as_view(
            template_name='recipes/contents_dev.html'
       ), name='user_recipes'),


    url(r'^data/(?P<slug>[-\w]+)/$', RecipeDetailView.as_view(),{"format":"json"},name='recipe_json_detail'),
    url(r'^data/$',RecipeListView.as_view(
            queryset=Recipe.objects.all().order_by('name'),
            template_name='recipes/index_dev.html'
            ),{"format":"json"},name='recipe_json_list'),
)

recipes/models.py
from django.db import models
from django.db.models import F
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.core.urlresolvers import reverse
from django.forms import ModelForm, Textarea
import datetime, decimal, fractions
import sys

UNIT_CHOICES = (
    (u'cup', u'cup'),
    (u'tbs', u'tablespoon'),
    (u'tsp', u'teaspoon'),
    (u'lb', u'pound'),
    (u'oz', u'ounce'),
    (u'box', u'box'),
    (u'pkg', u'package'),
    (u'can', u'can'),
    (u'oth', u'to taste'),
    (u'itm', u'item'),
    (u'qrt', u'quart'),
    (u'foz', u'fluid ounce'),
    )

UNIT_CONVERSIONS = {
    (u'cup',u'tbs'):16,
    (u'tbs',u'tsp'):3,
    (u'qrt',u'cup'):4,
    (u'cup',u'tsp'):48,
    (u'cup',u'foz'):8,
    (u'lb',u'oz'):16,
    (u'oth',u'tsp'):1,
}

def convert(unit_a,unit_b):
    if (unit_a,unit_b) in UNIT_CONVERSIONS:
        return UNIT_CONVERSIONS[(unit_a,unit_b)]
    elif (unit_b,unit_a) in UNIT_CONVERSIONS:
        return decimal.Decimal(str(1.0/UNIT_CONVERSIONS[(unit_b,unit_a)]))
    else:
        return 0 #should raise an exception

DISH_CHOICES = (
    (u'apptz', u'Appetizer'),
    (u'brd',u'Bread'),
    (u'bkfst', u'Breakfast'),
    (u'duov', u'Dutch Oven'),
    (u'dsrt', u'Dessert'),
    (u'main', u'Entree'),
    (u'salad', u'Salad'),
    (u'sdwch', u'Sandwich'),
    (u'side', u'Side Dish'),
    (u'snack', u'Snack'),
    (u'soup', u'Soup'),
    (u'oth',u'Other'),
    )

DEPT_CHOICES = (
    (u'bkry', u'Bakery'),
    (u'drygd', u'Dry Goods'),
    (u'dairy', u'Dairy'),
    (u'deli', u'Delicatessan'),
    (u'frzn', u'Frozen'),
    (u'prdc', u'Produce'),
    (u'meat', u'Meat and Fish'),
    (u'juice', u'Drinks '),
    (u'canned', u'Canned Goods'),
    (u'spice', u'Spices, Condiments, Sauces'),
    )

class Recipe(models.Model):
    name = models.CharField(max_length=100)
    date_added = models.DateTimeField('date added', auto_now_add=True)
    origin = models.CharField(max_length=200, blank=True)
    cooking_time = models.PositiveIntegerField('cook time',blank=True, null=True)
    prep_time = models.PositiveIntegerField('prep time', blank=True, null=True)
    slug = models.SlugField(unique=True)
    notes = models.TextField(blank=True)
    dish = models.CharField(max_length=6, choices=DISH_CHOICES)
    servings = models.PositiveIntegerField('number of servings',default=4)
    image_url = models.URLField(blank=True)


    def nutrition(self):
        nut_dict = {'calories':0,'carbohydrate':0,'protein':0,'fat':0,'weight':0,'errors':''}
        for item in self.recipeingredient_set.all():
            if item.ingredient.nutrition_ingredient_id != None:
                nut_ing = item.ingredient.nutrition_ingredient
                rec_amount = item.amount
                rec_unit = item.unit
                nut_weight = 0
                nut_amount = 1
                for unit_amt in nut_ing.nutritionunit_set.all():
                    if unit_amt.unit == rec_unit:
                        nut_amount = unit_amt.amount
                        nut_weight = unit_amt.weight
                        break
                else:
                    for unit_amt in nut_ing.nutritionunit_set.all():
                        conv_fact = convert(unit_amt.unit,rec_unit)
                        if conv_fact != 0:
                            nut_amount = unit_amt.amount/conv_fact
                            nut_weight = unit_amt.weight
                            break
                    else:
                        nut_dict['errors'] += "No unit-conv: " + item.ingredient.name + " " + rec_unit + " to " + str([n.unit for n in nut_ing.nutritionunit_set.all()]) + "\n"
                tags = nut_dict.keys()
                tags.remove('errors')
                tags.remove('weight')
#                nut_dict['errors'] += str(item) + "\n"
                nut_dict['weight'] += nut_weight*nut_amount
                for tag in tags:
                    nut_calc = int((getattr(nut_ing,tag)*rec_amount*nut_weight*nut_amount)/100)
                    nut_dict[tag] += nut_calc
#                    nut_dict['errors'] += "-" + str(rec_amount*nut_weight/(100*nut_amount)) + " " + tag[:4] + ":" + str(nut_calc)
#                nut_dict['errors'] += "\n"

        tags = nut_dict.keys()
        tags.remove('errors')
        for key in tags:
            nut_dict[key] /= self.servings
        nut_dict['weight'] = int(nut_dict['weight'])
        return nut_dict
            

    def first_letter(self):
        return self.name[0]

    def  __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("recipe_json_detail",args=[self.slug])

class Ingredient(models.Model):
    name = models.CharField(max_length=100, unique=True)
    grocery_department = models.CharField(max_length=6, choices=DEPT_CHOICES, blank=True)
    nutrition_ingredient = models.ForeignKey('NutritionIngredient',blank=True)

    def __unicode__(self):
        return self.name

    class Meta:
        ordering = ['name']

class FoodPicture(models.Model):
    recipe = models.ForeignKey(Recipe)
    img_address = models.URLField(verbose_name="Image URL (required)", 
                                  help_text="Usually ends in <code>.jpg</code>.")
    link_address = models.URLField(verbose_name="Link (optional)", 
                                   blank = True,
                                   help_text="Main image page.")
    caption = models.TextField(blank=True,
                               verbose_name="Caption (optional)")

class FoodPictureForm(ModelForm):
    class Meta:
        model = FoodPicture
        exclude = ('recipe',)
        widgets = {
            'caption': Textarea(attrs = {'cols':50, 'rows':5})
            }

class RecipeIngredient(models.Model):
    ingredient = models.ForeignKey(Ingredient)
    recipe = models.ForeignKey(Recipe)
    amount = models.DecimalField(max_digits=6, decimal_places=4)
    unit = models.CharField(max_length = 4, choices=UNIT_CHOICES)

    def format_amount(self):
        retval = ''
        intPart = self.amount.quantize(decimal.Decimal('1.'), rounding=decimal.ROUND_DOWN)
        decPart = self.amount % 1
        fracPart = fractions.Fraction.from_decimal(decPart).limit_denominator(16)
        if intPart:
            retval += str(intPart) + ' '
        if fracPart:
            retval += str(fracPart) + ' '
        if self.get_unit_display() != 'item':
            retval += self.get_unit_display()
            if self.amount > 1:
                retval += 's'
        return retval

    def __unicode__(self):
        if self.get_unit_display() == 'to taste':
            return u'{1} {0}'.format(self.format_amount(), self.ingredient)
        else:
            return u'{0} {1}'.format(self.format_amount(), self.ingredient)

class InstructionStep(models.Model):
    this_step = models.TextField('step')
    recipe = models.ForeignKey(Recipe)

    def __unicode__(self):
        return self.this_step

    class Meta:
        verbose_name = 'instruction'

class NutritionIngredient(models.Model):
    name = models.CharField(max_length=100)
    weight_1 = models.DecimalField(max_digits=9,decimal_places=2,default=0,blank=True)
    weight_1_desc = models.CharField(max_length=120,blank=True)
    weight_2 = models.DecimalField(max_digits=9,decimal_places=2,default=0,blank=True)
    weight_2_desc = models.CharField(max_length=120,blank=True)
    water = models.DecimalField(max_digits=10,decimal_places=2,default=0,blank=True)
    calories = models.IntegerField(default=0,blank=True)
    protein = models.DecimalField(max_digits=10,decimal_places=2,default=0,blank=True)
    fat = models.DecimalField(max_digits=10,decimal_places=2,default=0,blank=True)
    ash = models.DecimalField(max_digits=10,decimal_places=2,default=0,blank=True)
    carbohydrate = models.DecimalField(max_digits=10,decimal_places=2,default=0,blank=True)
    fiber = models.DecimalField(max_digits=10,decimal_places=1,default=0,blank=True)
    sugar = models.DecimalField(max_digits=10,decimal_places=2,default=0,blank=True)
    calcium = models.IntegerField(default=0,blank=True)
    iron = models.DecimalField(max_digits=10,decimal_places=2,default=0,blank=True)
    magnesium = models.IntegerField(default=0,blank=True)
    phosphorus = models.IntegerField(default=0,blank=True)
    potassium = models.IntegerField(default=0,blank=True)
    sodium = models.IntegerField(default=0,blank=True)
    zinc = models.DecimalField(max_digits=10,decimal_places=2,default=0,blank=True)
    copper = models.DecimalField(max_digits=10,decimal_places=3,default=0,blank=True)
    manganese = models.DecimalField(max_digits=10,decimal_places=2,default=0,blank=True)
    selenium = models.DecimalField(max_digits=10,decimal_places=1,default=0,blank=True)
    vitamin_c = models.DecimalField(max_digits=10,decimal_places=1,default=0,blank=True)
    thiamin = models.DecimalField(max_digits=10,decimal_places=3,default=0,blank=True)
    riboflavin = models.DecimalField(max_digits=10,decimal_places=3,default=0,blank=True)
    niacin = models.DecimalField(max_digits=10,decimal_places=3,default=0,blank=True)
    panto_acid = models.DecimalField(max_digits=10,decimal_places=3,default=0,blank=True)
    vitamin_b6 = models.DecimalField(max_digits=10,decimal_places=3,default=0,blank=True)
    folate = models.IntegerField(default=0,blank=True)
    folic_acid = models.IntegerField(default=0,blank=True)
    food_folate = models.IntegerField(default=0,blank=True)
    folate_dfe = models.IntegerField(default=0,blank=True)
    choline = models.DecimalField(max_digits=10,decimal_places=2,default=0,blank=True)
    vitamin_b12 = models.DecimalField(max_digits=10,decimal_places=2,default=0,blank=True)
    vitamin_a_iu = models.IntegerField(default=0,blank=True)
    vitamin_a_rae = models.IntegerField(default=0,blank=True)
    retinol = models.IntegerField(default=0,blank=True)
    alpha_carotene = models.IntegerField(default=0,blank=True)

recipes/templates/recipes/contents.html
{% extends "base.html" %}

{% block title %}
{% regroup recipe_list by get_dish_display as contents_list %}
{% if contents_list|length > 1 %}
Table of Contents
{% else %}
  {% for dish in contents_list %}
    {{ dish.grouper }}s
  {% endfor %}
{% endif %}
{% endblock %}

{% block contents %}

{% regroup recipe_list by get_dish_display as contents_list %}
<h1 style="text-align:center;">
{% if contents_list|length > 1 %}
Table of Contents
{% else %}
  {% for dish in contents_list %}
    {{ dish.grouper }}s
  {% endfor %}
{% endif %}
</h1>

{% if recipe_list|length < 7 %}
<div style="width:27%;margin:auto;">
{% else %}    
<div class="selectlist">
{% endif %}
      
    {% if contents_list|length > 1 %}
  <ul style="list-style:inside none;margin-left:2em;padding-left:0px;">
    {% for dish in contents_list %}
    <li > <h3>{{ dish.grouper }}</h3> </li>
    <ul style="list-style-type:none;margin-left:-2em;padding-left:0px;">
      {% for recipe in dish.list %}
      <li> <a href="/recipes/{{recipe.slug}}/">{{ recipe }}</a></li>
      {% endfor %}
    </ul>
    {% endfor %}
  </ul>
    {% else %}
    {% for dish in contents_list %}
    <ul style="list-style-type:none;margin-left:0px;padding-left:0px;">
      {% for recipe in dish.list %}
      <li> <a href="/recipes/{{recipe.slug}}/">{{ recipe }}</a></li>
      {% endfor %}
    </ul>
    {% endfor %}
    {% endif %}
</div>    
{% endblock contents %}

recipes/templates/recipes/detail.html
{% extends "base.html" %}

{% block title %}{{ object.name }}{% endblock %}

{% block contents %}
    <div style="width:600px;
		margin-left:auto;
		margin-right:auto;
		overflow:auto;
		margin-bottom:3ex;">
      <h1>{{ object.name }}</h1>
      <div style="width:30%;float:left;">
	<h3>Ingredients:</h3>
	<ul style="padding:0px;margin:0px;list-style-position:inside;">
	  {% for ingredient in object.recipeingredient_set.all %}
	  <li> {{ ingredient }} </li>
	  {% endfor %}
	</ul>
      </div>
      <div style="width:65%;float:right;">
	<h3>Directions:</h3>
	<ol style="padding:0px;margin:0px">
	  {% for instruction in object.instructionstep_set.all %}
	  <li> {{ instruction }}</li>
	  {% endfor %}
	</ol>
	<ul>
	  {% with nut_info=object.nutrition %}
	  <li>Calories: {{ nut_info.calories }}</li>
	  <li>Carbohydrate: {{ nut_info.carbohydrate }} </li>
	  <li>Protein: {{ nut_info.protein }} </li>
	  <li>Fat: {{ nut_info.fat }} </li>
	  <li>Errors: {{ nut_info.errors|linebreaks }}</li>
	  {% endwith %}
	<ul>
      </div>
    </div>
{% endblock contents %}

recipes/templates/recipes/detail_dev.html
{% extends "base_bs.html" %}
{% load comments %}
{% load persona_name %}

{% block container %}
<div class="row">
  <div class="span6 offset3">
    <h1>
    {% if user.is_authenticated %}
    <span class="pull-right" id="outer_bookmark">
      {% if object in user.get_profile.fav_recipes.all %}
	<i class="icon-bookmark" id="bookmark"></i>
	{% else %}
	<i class="icon-bookmark-empty" id="bookmark"></i>
	{% endif %}
    </span>
    {% endif %}
      {{ object.name }}
    </h1>
    <h5>
      {% if perms.recipes.add_recipe %}
      <span class="pull-right">
	<a href="/admin/recipes/recipe/{{object.id}}/"><i class="icon-edit"></i></a>
      </span>
      {% endif %}
      From <em>{{object.origin}}</em>
    </h5>
  </div>
  <div class="span2 social">
    <span id="pin_it">
      <a href="http://pinterest.com/pin/create/button/?url={{ request.get_host|urlencode}}/{{ object.build_absolute_uri|urlencode }}&media={% if object.foodpicture_set.all %}{{ object.foodpicture_set.all.0.img_address|urlencode }}{% else %}http%3A%2F%2Ffarm9.staticflickr.com%2F8054%2F8112928661_489e902962.jpg{% endif %}&description={{ object.name|urlencode }}%20from%20Family%20Recipes" class="pin-it-button" count-layout="horizontal"><img border="0" src="//assets.pinterest.com/images/PinExt.png" title="Pin It" /></a>
    </span>
  </div>
</div>

<div class="row">
  
  <div class="span8 offset2">
    <div class="row">
      <div class="span3">
	<h3>Ingredients:</h3>
	<ul style="padding:0px;margin:0px;list-style-position:inside;" id="ing-list">
	  {% for ingredient in object.recipeingredient_set.all %}
	  <li data-ing="{{ ingredient.ingredient.name }}"
	      data-amt="{{ ingredient.amount }}"
	      data-unit="{{ ingredient.unit }}">
            {{ ingredient }}
          </li>
	  {% endfor %}
	</ul>
      </div>
      <div class="span5" id="directions">
	<h3>
	  <button class="btn btn-mini pull-right" id="change-view">Change View</button> 
	  Directions:
	</h3>
	<div id="traditional">
	  <ol style="padding:0px;margin:0px" >
	    {% for instruction in object.instructionstep_set.all %}
	    <li> {{ instruction }}</li>
	    {% endfor %}
	  </ol>
	</div>
	<div id="one-by-one" style="display:none">
	  <ul class="nav nav-tabs">
	  {% for instruction in object.instructionstep_set.all %}
	  <li {% if forloop.first %}class="active"{% endif %}>
	    <a href="#step-{{ forloop.counter }}"
	       data-toggle="tab">
	      Step {{ forloop.counter }}
	    </a>
	  </li>	  
	  {% endfor %}
	  </ul>
	  <div class="tab-content">
	    {% for instruction in object.instructionstep_set.all %}
	    <div class="tab-pane{% if forloop.first %} active{% endif %}"
		 id="step-{{ forloop.counter }}">
	      <p class="lead">{{ instruction }}</p>
	    </div>
	    {% endfor %}
	  </div>
	</div>
      </div>
    </div>

    <div class="row">
      <hr />
      <div class="span3">
	<div class="well">
	  <h4>Nutrition Information</h4>
	  <ul>
	    {% with nut_info=object.nutrition %}
	    <li>Servings: {{object.servings}}</li>
	    <li>Serving Size: {{ nut_info.weight }}g</li>
	    <li>Calories: {{ nut_info.calories }}</li>
	    <li>Carbohydrate: {{ nut_info.carbohydrate }}g</li>
	    <li>Protein: {{ nut_info.protein }}g</li>
	    <li>Fat: {{ nut_info.fat }}g</li>
	    {#<li>Errors: {{ nut_info.errors|linebreaks }}</li>#}
	    {% endwith %}
	  </ul>
	</div>
      </div>
    <div class="span5">
      {% if object.foodpicture_set.all %}
      <div>
	<ul class="thumbnails">
	  {% for picture in object.foodpicture_set.all %}
	  {% if forloop.first %}
	  <li class="span3">
            {% else %}
	  <li class="span2">
	    {% endif %}
	    <a href="{% if picture.link_address %}{{picture.link_address}}{% else %}{{ picture.img_address }}{% endif %}" class="thumbnail">
	      <img src="{{picture.img_address}}" 
		   alt="{{object.name}}-{{forloop.counter}}" />
            </a>
	  </li>
	  {% if forloop.counter == 3 and not forloop.last %}
	</ul>
      </div>
      <h5 data-toggle="collapse"
	  data-target="#extra-pics">
	<i class="icon-plus-sign"></i> More Pictures
      </h5>
      <div class="collapse" id="extra-pics">
	<ul class="thumbnails">
	  {% endif %}
	  {% endfor %}
	</ul>
      </div>
      {% endif %}
      {% if user.is_authenticated %}
      <div>
	<button class="btn btn-small" data-toggle="collapse" data-target="#picture-form">
	  <i class="icon-plus-sign"></i> Add a Picture
	</button>
	<div id="picture-form" class="collapse">
	  <form action="picture/" method="POST">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <p>
	      <button class="btn btn-primary" type="submit" name="submit" value="Post">
		Add
	      </button>
	    </p>
	  </form>
	</div>
      </div>
      {% endif %}
    </div>
    </div>
    <div class="row">
      <hr />
      <div class="span5">
      <h5>Comments:</h5>
      {% get_comment_list for object as comment_list %}
      {% for comment in comment_list %}
      {% with comment.user as commenter %}
      <div class="well">
	<p>
	  {{ comment.comment }}
	</p>
	<p class="pull-right">
	  {% if commenter.first_name or commenter.last_name %}
          {{commenter.first_name}} {{commenter.last_name}}, 
	  {% else %}
          {{commenter.username|shortname}}, 
	  {% endif %}
	  <em>{{comment.submit_date|date:"M j, Y"}}</em>
	</p>
      </div>
      {% endwith %}
      {% empty %}
      <p>
	No comments yet.{% if user.is_authenticated %} Be the first to add one!{% endif %}
      </p>
      {% endfor %}
      </div>
      {% if user.is_authenticated %}
      <div class="span3">
      {% get_comment_form for object as form %}
      <form action="{% comment_form_target %}" method="post">
	<legend>Add a Comment</legend>
	{% csrf_token %}
	{% for field in form %}
	{% if field.is_hidden %}
	<div>{{ field }}</div>
	{% elif field.name in "nameemailurl" %}
	<div style="display:none">
	  {{ field }}
	</div>
	{% else %}
	{% if field.errors %}{{ field.errors }}{% endif %}
	<p
           {% if field.errors %} class="error"{% endif %}
           {% ifequal field.name "honeypot" %} style="display:none;"{% endifequal %}>
          {{ field.label_tag }} {{ field }}
	</p>
	{% endif %}
	{% endfor %}


	<input type="hidden" name="next" value="{{ request.get_full_path }}" />        
	<button class="btn btn-primary" type="submit" name="submit" value="Post">Post</button>
        <button class="btn" type="submit" name="preview" value="Preview">Preview</button>
      </form>
      </div>
      {% else %}
      Only registered users may comment.  
      <br />
      <a href="#" id="persona_login_sub">
        <img src="{{ STATIC_URL }}img/email_sign_in_black.png" />
      </a>
      {% endif %}
    </div>
  </div>
  
</div>
{% endblock container %}

{% block custom_script %}
<script>
$(document).ready(function() {
  $.ajaxSetup({
    crossDomain: false,
    beforeSend: function(xhr, settings) {
        if (/^(POST|PUT|DELETE)$/.test(settings.type)) {
            xhr.setRequestHeader("X-CSRFToken", "{{csrf_token}}");
        }
    }
  });
  $("#persona_login_sub").on("click", function() {
    $("#persona_login").trigger("click");
  });
  $("#outer_bookmark").on("click",function(event) {
    var method_type = "PUT";
    var cur_icn = $(this).children("i").first();
    if (cur_icn.hasClass("icon-bookmark")) {
      method_type = "DELETE";
    };
    $.ajax({
      type: method_type,
      data: { key: "val" },
      url: "/recipes/fav/{{object.slug}}/"
    }).done(function() {
      cur_icn.toggleClass("icon-bookmark icon-bookmark-empty");
    });

  });
  $("#change-view").on('click', function(event) {
      $("#directions").children("div").slideToggle( function() {
	  if (!$("#one-by-one").is(":hidden")) {
	      var first_text = $("#one-by-one .tab-content .active").text();
	      highlight_ings(first_text);
	  } else {
	      highlight_ings('');
	  };
      });
  });

  var highlight_ings = function(text) {
      var ing_list = $("#ing-list");
      $('strong',ing_list).contents().unwrap();
      $('em',ing_list).contents().unwrap();
      ing_list.children().each(function(idx, elt) {
	  var ing_list = $(elt).data('ing').split(/[^\w]+/);
	  for (var i=0, len=ing_list.length; i < len; i++) {
	      if (text.search(ing_list[i]) > 0) {
		  $(this).wrapInner("<strong />").wrapInner("<em />");
		  break;
	      };
	  };
      });
  };

  $('a[data-toggle="tab"]').on('shown',function(event) {
      var step_text = $($(event.target).attr("href")).text();
      highlight_ings(step_text);
  });
});
</script>
<script type="text/javascript" src="//assets.pinterest.com/js/pinit.js"></script>
{% endblock custom_script %}

recipes/templates/recipes/detailfirst.html
<html>
<head>
<title>{{ object.name }}</title>
</head>
<body>
<h1>{{ object.name }}</h1>

<h3>Ingredients:</h3>
<ul>
{% for ingredient in object.recipeingredient_set.all %}
  <li> {{ ingredient }} </li>
{% endfor %}
</ul>

<h3>Directions:</h3>
<ol>
{% for instruction in object.instructionstep_set.all %}
  <li> {{ instruction }}</li>
{% endfor %}
</ol>
</body>
</html>

recipes/templates/recipes/foodpicture_form.html
{% extends "base_bs.html" %}

{% block container %}
<div class="row">
<div class="span4 offset4">
<h2>Picture for {{ object.name }}</h2>
<form method="POST">
{% csrf_token %}
{{ form.as_p }}
<p><input type="submit" value="Submit"></p>
</form>
</span>
</div>
{% endblock container %}

recipes/templates/recipes/index.html
{% extends "base.html" %}

{% block title %} Recipe Index {% endblock %}

{% block contents %}
<h1 style="text-align:center;">Recipe Index</h1>


{% if recipe_list|length < 7 %}
<div style="width:27%;margin:auto;">
{% else %}    
<div class="selectlist">
{% endif %}

{% regroup recipe_list by first_letter as first_letter_list %}
  <ul style="list-style:inside none;margin-left:2em;padding-left:0px;">

    {% for letter in first_letter_list %}
    <li> <h3>{{ letter.grouper }}</h3>
    <ul style="list-style-type:none;margin-left:-2em;padding-left:0px;">
      {% for recipe in letter.list %}
      <li> <a href="/recipes/{{recipe.slug}}/">{{ recipe }}</a></li>
      {% endfor %}
    </ul>
    </li>
    {% endfor %}

  </ul>    
</div>    
{% endblock contents %}

recipes/templates/recipes/search_dev.html
{% extends "base_bs.html" %}

{% block container %}

<div class="span4 offset4" id="contents_div">
  <h1>
    Search Results
  </h1>
  <div class="row">
    <ul style="line-height:2">
      {% for recipe in recipe_list %}
      <li>
	<a href="{% url recipe_detail recipe.slug %}">{{recipe}}</a>
      </li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock container %}

{% block custom_script %}
{% endblock custom_script %}